### ISSUE TITLE
how to connect to an office 365 environment?

### ISSUE THREAD

**Issue by Nahomsk** [acieslik/CRMCustomizationToolForExcel#2]
Hi there, 

I am struggling to connect to a D365 environment.

do you have any examples or instructions on how to connect to an environment? 

thanks in advance,

Nahom

**Comment by acieslik** [comment]
Is it a version 8.2 or 9.x environment?

**Comment by Nahomsk** [comment]
its an 8.2 environment

**Comment by Nahomsk** [comment]
Apologies @acieslik it was an issue with the users licence. it was the service tenant user. but when i used a different account with sys admin role given. it worked just fine. 

Thanks for your efforts on adding support for this!
